### ISSUE TITLE
面談: データベース設計(ERD作成)

### ISSUE THREAD

**Issue by ryuki7** [ryuki7/dating-apps-master#9]
画面遷移図を参照してます。

1.モテ度・好感度・進展度の数値化方法とデータベース構造について。
例) 手を繋ぐ => 1点
　　キスをする => 5点　　　など。

2.手を繋ぐ => クリア
　キスをする => 失敗
などをどうやってデータベースに保存するのか。

3.適正アプリ診断はどのようなデータベース構造にすれば良いのか。元からデータベースで組み合わせの診断結果を用意するのが一番容易？
IFだとデータが多すぎる？

4.おすすめ機能(おすすめのデートプラン・予定日)をどうやって実装するのか。
データベースに用意するとなるとデータが多すぎる？
IFでもデータが多すぎる？

分かりづらかったらすみません🙇‍♂️

**Comment by kerochelo** [comment]
`users`(男性)
`partners`(女性)
`dates`(実際にデートをした情報を記録する)
`apps`(マスタ：マッチングアプリ)
`date_plans`(マスタ：デートプラン)

**Comment by kerochelo** [comment]
この記事いいかもです！
https://qiita.com/nishina555/items/a79ece1b54faf7240fac

**Comment by ryuki7** [comment]
> この記事いいかもです！
> https://qiita.com/nishina555/items/a79ece1b54faf7240fac

ありがとうございます！！
見てみます👀
